import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Theme } from "@/components/plugin/theme";
import "./globals.css";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <Theme attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </Theme>
      </body>
    </html>
  );
}
